# Generated by Django 4.0.1 on 2022-03-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('appid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobfunction', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('salary', models.CharField(max_length=100)),
            ],
        ),
    ]
