# Generated by Django 4.0.1 on 2022-03-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='appid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
