# Generated by Django 4.0.1 on 2022-03-01 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0003_alter_application_appid'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hremail',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
