# Generated by Django 4.0.1 on 2022-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_portal', '0004_application_hremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicantid', models.AutoField(primary_key=True, serialize=False)),
                ('candidateemail', models.CharField(max_length=100)),
                ('appid', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('birthdate', models.CharField(max_length=100)),
                ('expected_salary', models.CharField(max_length=100)),
                ('resume_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
